### ISSUE TITLE
can be used as a git dependency

### ISSUE THREAD

**Issue by workingjubilee** [Andrew-Shay/rust_vendor_base64#2]
I can add your crate by writing the following in my toml:
```toml
[dependencies]
vendor_base64 = { git = "https://github.com/Andrew-Shay/rust_vendor_base64" }
```

If you want people to actually copy your code, you should consider not arranging it in crate form, which makes it easy for them to not.
